### ISSUE TITLE
"Choose from word list" for RVG

### ISSUE THREAD

**Issue by spookylukey** [learnscripture/learnscripture.net#202]
@jerivas 

From https://github.com/learnscripture/learnscripture.net/pull/199#issuecomment-1426148477

> The only thing that is missing is the "Choose from word list" learning strategy

I've done some more work and added this. It involved fixing a fair number of bugs with punctuation and ordering. 

This is also the first time I've enabled "choose from word list" testing strategy (aka word suggestions) with a non-English translation. This is tricky, because the code which generates suggestions doesn't always do a very good job even with English, and I can't judge how well it works with Spanish.

For background, see https://github.com/learnscripture/learnscripture.net/blob/master/bibleverses/suggestions/__init__.py and https://github.com/learnscripture/learnscripture.net/issues/200

I've pushed this live. If you would be able to test it and see if it produces good enough results, that would be great.

**Comment by jerivas** [comment]
Thanks for enabling that! I went over a handful of Bible 101 verses and I think it's working well enough. I agree the predictions could be better (right now it's pretty obvious that some don't make sense at all), but one can always use the other testing methods. I say let's keep it live 👍

**Comment by spookylukey** [comment]
OK great, thanks for the feedback.

On that basis I'll switch the translation to public.
